import os
import json
import logging

logger = logging.getLogger("rag_bench.mock_utils")

def create_mock_dataset():
    """Generates a sample passage-grounded JSON dataset and raw documents if not present."""
    os.makedirs("data/processed", exist_ok=True)
    os.makedirs("data/raw", exist_ok=True)
    
    questions_file = "data/processed/questions.json"
    
    # Define 8 source documents containing distinct technical domains
    raw_docs = {
        "search_architecture_guide.md": (
            "Vector databases represent text chunks as dense floating-point arrays generated by embedding models. "
            "Cosine similarity is calculated as the dot product of two normalized vectors, reflecting their semantic closeness. "
            "In lexical search, BM25 assigns query relevance scores using term frequency and inverse document frequency. "
            "Reciprocal Rank Fusion (RRF) combines dense and sparse ranks by summing reciprocal ranks, bypassing raw score scaling issues. "
            "Rerankers employ cross-encoder architectures to analyze token attention relationships directly between query and context blocks."
        ),
        "parent_document_retrieval.md": (
            "Parent-Document retrieval indexes small child chunks to maintain precise lexical or semantic alignment with short search queries. "
            "However, during synthesis, the retriever maps the matched child ID to its larger parent document segment. "
            "This ensures the generative LLM receives sufficient surrounding context padding to ground its answer accurately. "
            "Contextual compression uses similarity filters to prune noisy sentences from the retrieved text, but is redundant when parent padding is desired."
        ),
        "query_refinement_methods.md": (
            "Hypothetical Document Embedding (HyDE) leverages an LLM to generate a synthetic response to a user query. "
            "The synthetic document is then embedded and used to query a vector index, bypassing lexical mismatch bottlenecks. "
            "Query rewriting generates multiple alternative query formulations, broadening term expansion for keyword retrieval. "
            "BM25 is a term-matching algorithm that performs poorly on synthetic narratives due to lexical differences between synthetic and actual texts."
        ),
        "chunking_strategies.md": (
            "Fixed-size chunking divides documents into uniform segments of N tokens with a configurable overlap window. "
            "Recursive character splitting uses structural delimiters like paragraph breaks and newlines to produce semantically coherent fragments. "
            "Semantic chunking embeds adjacent sentences and splits where the cosine distance between consecutive sentence vectors exceeds a percentile threshold. "
            "Chunk size directly impacts retrieval granularity: smaller chunks improve precision but may lose surrounding context."
        ),
        "embedding_models.md": (
            "Sentence transformers encode variable-length text into fixed-dimensional dense vectors for semantic search. "
            "Models like all-MiniLM-L6-v2 produce 384-dimensional embeddings optimized for cosine similarity matching. "
            "Fine-tuning embeddings on domain-specific corpora can significantly boost retrieval accuracy in specialized fields. "
            "Dimensionality reduction techniques such as PCA or Matryoshka representations can compress embeddings without major quality loss."
        ),
        "evaluation_metrics.md": (
            "Recall at K measures the fraction of relevant documents retrieved within the top K results. "
            "Mean Reciprocal Rank (MRR) computes the reciprocal of the rank of the first relevant document. "
            "Normalized Discounted Cumulative Gain (NDCG) accounts for the position of relevant items using logarithmic decay weighting. "
            "Hit Rate at K is a binary metric returning 1 if any relevant document appears in the top K, and 0 otherwise."
        ),
        "reranking_methods.md": (
            "Cross-encoder rerankers process query-document pairs jointly through a transformer to produce fine-grained relevance scores. "
            "Unlike bi-encoders, cross-encoders attend to both query and document tokens simultaneously enabling richer interaction modeling. "
            "Reranking is typically applied as a second-stage process after an initial fast retrieval pass to re-order the candidate set. "
            "Latency increases linearly with the number of candidates reranked since each pair requires a full forward pass."
        ),
        "rag_generation.md": (
            "Retrieval-Augmented Generation (RAG) grounds LLM responses in external knowledge by injecting retrieved context into the prompt. "
            "Faithfulness measures whether generated statements are supported by the retrieved passages. "
            "Answer relevancy evaluates how directly the response addresses the original user query without extraneous information. "
            "Context window limits constrain the total amount of retrieved text that can be provided to the generator."
        )
    }
    
    # Save raw documents to disk
    for doc_name, content in raw_docs.items():
        doc_path = os.path.join("data/raw", doc_name)
        if not os.path.exists(doc_path):
            with open(doc_path, "w", encoding="utf-8") as f:
                f.write(content)
            logger.info(f"Created sample raw document: {doc_path}")

    # Generate 30 distractor documents to create search variance
    for i in range(1, 31):
        doc_name = f"distractor_{i:03d}.md"
        doc_path = os.path.join("data/raw", doc_name)
        if not os.path.exists(doc_path):
            content = (
                f"This is distractor document number {i}. It discusses technical parameters and system configurations "
                f"completely unrelated to the RAG evaluation framework. Specifically, it reviews network bandwidth limits, "
                f"database clustering protocols, and security authentication firewalls. We detail performance stats for "
                f"CPU load, disk read/write latency, and RAM cache allocations in remote servers located in data center zone {i * 7}."
            )
            with open(doc_path, "w", encoding="utf-8") as f:
                f.write(content)
            logger.info(f"Created distractor raw document: {doc_name}")

    # 15 questions spanning all 8 source documents
    mock_questions = [
        {
            "id": "q_001",
            "question": "How does reciprocal rank fusion combine dense and sparse search indices?",
            "ground_truth_answer": "RRF aggregates rankings from dense and sparse search by summing reciprocal ranks, avoiding issues with scaling incompatible raw scores.",
            "ground_truth_contexts": ["Reciprocal Rank Fusion (RRF) combines dense and sparse ranks by summing reciprocal ranks, bypassing raw score scaling issues."],
            "ground_truth_chunk_ids": {},
            "source_document_ids": ["search_architecture_guide.md"]
        },
        {
            "id": "q_002",
            "question": "What is the structural objective of parent document retrieval?",
            "ground_truth_answer": "Parent-Document retrieval indexes small child spans for precise matching, then returns larger parent blocks to supply the generator with enough context.",
            "ground_truth_contexts": ["Parent-Document retrieval indexes small child chunks to maintain precise lexical or semantic alignment with short search queries."],
            "ground_truth_chunk_ids": {},
            "source_document_ids": ["parent_document_retrieval.md"]
        },
        {
            "id": "q_003",
            "question": "Why is HyDE incompatible with sparse BM25 retrieval?",
            "ground_truth_answer": "HyDE creates a synthetic narrative designed for vector space matching. BM25 suffers from lexical mismatches when queried with long synthetic documents.",
            "ground_truth_contexts": ["BM25 is a term-matching algorithm that performs poorly on synthetic narratives due to lexical differences between synthetic and actual texts."],
            "ground_truth_chunk_ids": {},
            "source_document_ids": ["query_refinement_methods.md"]
        },
        {
            "id": "q_004",
            "question": "How does cosine similarity measure the closeness of two text embeddings?",
            "ground_truth_answer": "Cosine similarity is calculated as the dot product of two normalized vectors, reflecting their semantic closeness in the embedding space.",
            "ground_truth_contexts": ["Cosine similarity is calculated as the dot product of two normalized vectors, reflecting their semantic closeness."],
            "ground_truth_chunk_ids": {},
            "source_document_ids": ["search_architecture_guide.md"]
        },
        {
            "id": "q_005",
            "question": "What is the difference between fixed-size and semantic chunking?",
            "ground_truth_answer": "Fixed-size chunking divides documents into uniform segments of N tokens, while semantic chunking splits where cosine distance between consecutive sentence vectors exceeds a threshold.",
            "ground_truth_contexts": ["Fixed-size chunking divides documents into uniform segments of N tokens with a configurable overlap window.", "Semantic chunking embeds adjacent sentences and splits where the cosine distance between consecutive sentence vectors exceeds a percentile threshold."],
            "ground_truth_chunk_ids": {},
            "source_document_ids": ["chunking_strategies.md"]
        },
        {
            "id": "q_006",
            "question": "How does recursive character splitting decide where to break text?",
            "ground_truth_answer": "Recursive character splitting uses structural delimiters like paragraph breaks and newlines to produce semantically coherent fragments.",
            "ground_truth_contexts": ["Recursive character splitting uses structural delimiters like paragraph breaks and newlines to produce semantically coherent fragments."],
            "ground_truth_chunk_ids": {},
            "source_document_ids": ["chunking_strategies.md"]
        },
        {
            "id": "q_007",
            "question": "What output dimensionality do sentence transformer models like MiniLM produce?",
            "ground_truth_answer": "Models like all-MiniLM-L6-v2 produce 384-dimensional embeddings optimized for cosine similarity matching.",
            "ground_truth_contexts": ["Original Model outputs 384-dimensional vectors."],
            "ground_truth_chunk_ids": {},
            "source_document_ids": ["embedding_models.md"]
        },
        {
            "id": "q_008",
            "question": "How does Recall at K differ from Hit Rate at K?",
            "ground_truth_answer": "Recall@K measures the fraction of relevant documents retrieved, while Hit Rate@K is binary — 1 if any relevant document appears in top K, 0 otherwise.",
            "ground_truth_contexts": ["Recall at K measures the fraction of relevant documents retrieved within the top K results.", "Hit Rate at K is a binary metric returning 1 if any relevant document appears in the top K, and 0 otherwise."],
            "ground_truth_chunk_ids": {},
            "source_document_ids": ["evaluation_metrics.md"]
        },
        {
            "id": "q_009",
            "question": "What is NDCG and how does it weight document positions?",
            "ground_truth_answer": "NDCG accounts for the position of relevant items using logarithmic decay weighting, giving higher credit to relevant items ranked near the top.",
            "ground_truth_contexts": ["Normalized Discounted Cumulative Gain (NDCG) accounts for the position of relevant items using logarithmic decay weighting."],
            "ground_truth_chunk_ids": {},
            "source_document_ids": ["evaluation_metrics.md"]
        },
        {
            "id": "q_010",
            "question": "Why are cross-encoder rerankers slower than bi-encoder retrieval?",
            "ground_truth_answer": "Cross-encoders process query-document pairs jointly through a full forward pass for each pair, causing latency to increase linearly with the number of candidates.",
            "ground_truth_contexts": ["Latency increases linearly with the number of candidates reranked since each pair requires a full forward pass."],
            "ground_truth_chunk_ids": {},
            "source_document_ids": ["reranking_methods.md"]
        },
        {
            "id": "q_011",
            "question": "How do cross-encoders differ from bi-encoders in relevance scoring?",
            "ground_truth_answer": "Unlike bi-encoders, cross-encoders attend to both query and document tokens simultaneously, enabling richer interaction modeling for fine-grained relevance.",
            "ground_truth_contexts": ["Unlike bi-encoders, cross-encoders attend to both query and document tokens simultaneously enabling richer interaction modeling."],
            "ground_truth_chunk_ids": {},
            "source_document_ids": ["reranking_methods.md"]
        },
        {
            "id": "q_012",
            "question": "What does faithfulness measure in RAG evaluation?",
            "ground_truth_answer": "Faithfulness measures whether the generated statements in the LLM response are supported by the retrieved passages.",
            "ground_truth_contexts": ["Faithfulness measures whether generated statements are supported by the retrieved passages."],
            "ground_truth_chunk_ids": {},
            "source_document_ids": ["rag_generation.md"]
        },
        {
            "id": "q_013",
            "question": "How does BM25 assign relevance scores to documents?",
            "ground_truth_answer": "BM25 assigns query relevance scores using term frequency and inverse document frequency to surface keyword-matching documents.",
            "ground_truth_contexts": ["In lexical search, BM25 assigns query relevance scores using term frequency and inverse document frequency."],
            "ground_truth_chunk_ids": {},
            "source_document_ids": ["search_architecture_guide.md"]
        },
        {
            "id": "q_014",
            "question": "Why is contextual compression redundant with parent-document retrieval?",
            "ground_truth_answer": "Parent-Document retrieval broadens context by mapping child IDs to larger parent segments. Contextual compression strips that padding away, nullifying the indexing design.",
            "ground_truth_contexts": ["Contextual compression uses similarity filters to prune noisy sentences from the retrieved text, but is redundant when parent padding is desired."],
            "ground_truth_chunk_ids": {},
            "source_document_ids": ["parent_document_retrieval.md"]
        },
        {
            "id": "q_015",
            "question": "How does chunk size affect retrieval granularity?",
            "ground_truth_answer": "Smaller chunks improve precision by targeting narrow text spans, but may lose surrounding context needed for accurate answer generation.",
            "ground_truth_contexts": ["Chunk size directly impacts retrieval granularity: smaller chunks improve precision but may lose surrounding context."],
            "ground_truth_chunk_ids": {},
            "source_document_ids": ["chunking_strategies.md"]
        }
    ]
    
    # Dynamically assign unique ground truth chunk IDs for each question to ensure metric variance
    for idx, item in enumerate(mock_questions, start=1):
        item["ground_truth_chunk_ids"] = {
            "fixed_512": [f"c_fixed_512_{idx:03d}"],
            "fixed_1024": [f"c_fixed_1024_{idx:03d}"],
            "recursive": [f"c_rec_{idx:03d}"],
            "semantic": [f"c_sem_{idx:03d}"]
        }

    with open(questions_file, "w", encoding="utf-8") as f:
        json.dump(mock_questions, f, indent=2)
    logger.info(f"Refreshed sample dataset at: {questions_file} ({len(mock_questions)} questions)")

def mock_llm_client(prompt: str) -> str:
    """Mock LLM response generator to enable out-of-the-box local execution."""
    prompt_lower = prompt.lower()
    
    if "alternative search queries" in prompt_lower:
        lines = prompt.split("\n")
        question = lines[-1].replace("Question:", "").strip()
        words = question.split()
        kw = " ".join([w for w in words if len(w) > 4][:4])
        return f"Alternative query for {kw}\nHow is {kw} implemented"
        
    elif "hypothetical passage" in prompt_lower:
        lines = prompt.split("\n")
        question = lines[-1].replace("Question:", "").strip()
        return f"This hypothetical technical context describes concepts related to '{question}'. It explains how the architecture is constructed and deployed."
        
    elif "faithfulness" in prompt_lower:
        return "0.92"
        
    elif "answer relevancy" in prompt_lower:
        return "0.88"
        
    elif "answer correctness" in prompt_lower:
        return "0.85"
        
    else:
        return "This is a simulated RAG response constructed from matching document segments."
